minio:
    accessKey: minioadmin
    bucket:
        pathurlFiles: files
        pathurlImages: images
    bucket-name: commons
    endpoint: http://bienhoa.cf:9000
    file-size: 1073741824
    image-size: 10485760
    port: 9000
    secretKey: minioadmin
    secure: false
spring:
    datasource:
        password: P@ssword*123
        url: jdbc:postgresql://bienhoa.cf:5432/blog_dev?useSSL=false
        username: dev
    flyway:
        password: P@ssword*123
        url: jdbc:postgresql://bienhoa.cf:5432/blog_dev?useSSL=false
        user: dev
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true
